# Generated by Django 5.1 on 2024-08-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_pelicula_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaEstreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.DurationField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('fecha_estreno', models.DateField()),
            ],
        ),
    ]
